### ISSUE TITLE
模型展拍

### ISSUE THREAD

**Issue by zhongl** [zhongl/zhongl.github.com#31]
<input type='hidden' name='id' value='take photos in shizuoka hobby show' />

![](http://imglf6.nosdn0.126.net/img/c0NkZC8xc3QzeVRlbFF2cVpVcUZSMk4yd1BmMFFJSm16YTU5U2JuL3lONHh2a3M2S2lQaDJBPT0.jpg?imageView&thumbnail=1680x0&quality=96&stripmeta=0&type=jpg)

> SHIZUOKA HOBBY SHOW 2019

这是第二次去静冈模型展, 依旧没有装备微距镜头, 全部的希望都寄托于 **黑卡M5** 了. 此行自己觉得合格的片子要比上次多了不少, 主要原因可能是我喜欢拍的 **场景类模型** 较多吧.

> 为什么要选择场景类模型作为拍摄对象呢? 

我只是一个模型新手, 相较于参展的大多资深人士相比, 我只能算外行来拍个热闹的. **单品模型** 对我几乎没有什么吸引力, 哪怕是非常优秀的作品, 我也不识泰山啊. 相反, **场景类模型** (以下简称**场景**)从摄影的角度来看, 画面有故事, 细节更丰富, 值得品味很久. 

**场景** 中战争题材的作品最为常见, 很容易让人联想到一些影视作品的画面上. 拍摄中, 我也自然的去选择将这类 **场景** 往往影视画风上进行还原.

展品的放置是服务于 **观摩** 而非 **拍摄** 的, 对拍摄者的挑战还是蛮多的.

## 构图

展品陈列的密度太大导致想要拍摄主体全貌, 通常无法规避周围的干扰因素, 如介绍卡片, 人流, 其它作品等.

![LRG_DSC05907](https://user-images.githubusercontent.com/419346/57689065-6cc8ed00-7671-11e9-92ae-e84c2054c1a8.jpg)

## 光线

会场的光源主要来自屋顶, 遇到模型里有反光的材料, 就会让画面的真实感降低不少.

![Landing](http://imglf6.nosdn0.126.net/img/c0NkZC8xc3QzeVRlbFF2cVpVcUZSeVk3OGx1a0E3d0hQUmtESk9LcTZwSTdSclBURW1EQmt3PT0.jpg?imageView&thumbnail=1680x0&quality=96&stripmeta=0&type=jpg)

## 景深
 
在尝试各种变换缓解了 **构图** 和 **光线** 的问题后, 景深的控制又变得着实让人头疼.

![Grass](http://imglf5.nosdn0.126.net/img/c0NkZC8xc3QzeVRlbFF2cVpVcUZSeklVdCtCUGtnZmpjWUp4VEJFRWMvVmhWV0hvZzJkTVpnPT0.jpg?imageView&thumbnail=1680x0&quality=96&stripmeta=0&type=jpg)
 
## 心得

实践下来, 在非常有效的时间和空间制约下, 解决上述三个问题的有效方案是: **局部俯拍**.

![Street Fight](http://imglf6.nosdn0.126.net/img/c0NkZC8xc3QzeVMvaXgzTjcwYzlTWWhwQmpUM3RnaCtiQUhaMjdqWXJiTzlWejR2cms2UVd3PT0.jpg?imageView&thumbnail=1680x0&quality=96&stripmeta=0&type=jpg)

这里的俯拍不是严格的垂直, 而是根据主体选择合适的角度以规避 **反光**, 控制 **景深**  以求得 **主体细节** 与  **虚化干扰** 之间的平衡.

值得一提的是, 有少数展品的作者为了让作品更好被观赏(其实也是利于拍摄的), 确实花了心思. 比如提供 

- **黑色背景幕布** 

    ![Black Background](http://imglf3.nosdn0.126.net/img/c0NkZC8xc3QzeVJ0T0szckNYYlJ4V1VTV0F1RUNtbmVFci9qQmg3WEpxdFI0cTU5Mlc2STNnPT0.jpg?imageView&thumbnail=1680x0&quality=96&stripmeta=0&type=jpg)

- **图片背景**

    ![Pic Background](http://imglf5.nosdn0.126.net/img/c0NkZC8xc3QzeVJ0T0szckNYYlJ4VFpjWlhTaTg3b3JSWmlnZ3pycm5ZWlFPTzFRSmZuNDlnPT0.jpg?imageView&thumbnail=1680x0&quality=96&stripmeta=0&type=jpg)

吐槽一下, 有些 **场景** 作品被保护于 **玻璃罩** 之内, 如果没有偏光镜的话, 几乎没法拍摄, 甚至连肉眼观赏的效果都很差, 我只能表示遗憾了.

## 下次

2017年我第一次观展, 带的是 **D750 + 2470** 拍的时候很激动, 然后出来的片子都没法看, 最大的教训就是 **拍模型最近对焦距离是首要前提**. 

这次改用 **黑卡M5** 能够里主体更近了, 构图的选择空间也大了不少. 去之前其实也是考虑过微距镜头的, 但用的机会是实在太少, 而且会场人挤, 挂机穿梭也是件难受的事情. 其实, 用手机拍反而有意外的效果, 下次可以尝试. 

![image](https://user-images.githubusercontent.com/419346/57750514-2927bf00-7715-11e9-8b84-36b41915d2bd.png)

> 同行的朋友用手机拍的

仔细回顾片子, 发现自己忽略了 **场景** 的故事. 只是单纯的从喜好的直觉去拍摄, 然而选择的视角是否抓住了作品的精髓, 我是完全没有思考过的. 这是下次重点需要改进的地方.

期待明年!

**Comment by ketingli1** [comment]
厉害厉害
